# Generated by Django 3.1.7 on 2021-03-31 16:55

import bookmarks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to=bookmarks.models.get_path_file),
        ),
    ]
