# Generated by Django 3.1.7 on 2021-06-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20210613_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookmarks.folders'),
        ),
    ]
