# Generated by Django 3.1.7 on 2021-03-31 16:55

from django.db import migrations, models
import sites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(unique=True)),
                ('icons', models.ImageField(blank=True, null=True, upload_to=sites.models.get_path_site_icons)),
            ],
        ),
    ]
